In [5]:
import numpy as np

In [6]:
train_image = np.random.randint(0, 256, size=(10, 10))

test_image = np.random.randint(0, 256, size=(10, 10))

In [7]:
print("Train Data:\n", train_image)
print("\nTest Data:\n", test_image)

Train Data:
 [[137 118 132 105  38 120 212 164  46  81]
 [ 92  43 106 200 108 201 118  99 177 182]
 [224 254 155  57 142  33  89 227 146 195]
 [ 30 225 197  14 249 232 173  10 179  68]
 [215 101 251 158  73 227 105  45 115 144]
 [ 92 139 218 191 139 129  80 235 218 239]
 [121 176 122   7  90 244  58  69 138 238]
 [ 31 129 219 224 244  27 122 221 243  31]
 [ 26 175  95 107 217 153 210 211  80 111]
 [105 124 103 135  74 252 158  39 188  34]]

Test Data:
 [[ 33  94  59 228 102 121 221  55 209 127]
 [ 37 216  20 132 236 104 173  36 239  95]
 [ 79 231  47  21 155 203 251 161 236 153]
 [ 20 254  42  79 177  38 214 203 176 248]
 [151  85  79 198 172 189  19 194 188 154]
 [189  73  29  40 114 197  37 183 139   9]
 [130 248 103  43 245 120 178 101 136 182]
 [228 203 225 213 174 249 175  49  94  14]
 [137 117 118 145 192  14 233 233 188 123]
 [204  25 112 251  63 228 201  24 251 227]]


In [8]:
l1_distance = np.sum(np.abs(test_image - train_image))

l2_distance = np.sqrt(np.sum((test_image - train_image) ** 2))

print("L1 distance:", l1_distance)
print("L2 distance:", l2_distance)

L1 distance: 7961
L2 distance: 991.0353172314294
